/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppPedidosRouteImport } from './routes/_app/pedidos'
import { Route as AppExpedicaoRouteImport } from './routes/_app/expedicao'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/_app/configuracoes.index'
import { Route as OauthBlingCallbackRouteImport } from './routes/oauth/bling/callback'
import { Route as ApiMlCallbackRouteImport } from './routes/api/ml/callback'
import { Route as ApiMlAuthRouteImport } from './routes/api/ml/auth'
import { Route as ApiDebugEtiquetaTesteRouteImport } from './routes/api/debug/etiqueta-teste'
import { Route as AppConfiguracoesBlingRouteImport } from './routes/_app/configuracoes.bling'
import { Route as ApiPublicHooksBlingSyncProductsRunRouteImport } from './routes/api/public/hooks/bling-sync-products-run'
import { Route as ApiPublicHooksBlingSyncProductsDailyRouteImport } from './routes/api/public/hooks/bling-sync-products-daily'
import { Route as ApiPublicHooksBlingRefreshRouteImport } from './routes/api/public/hooks/bling-refresh'
import { Route as ApiPublicHooksBlingPedidosRouteImport } from './routes/api/public/hooks/bling-pedidos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedicaoRoute = AppExpedicaoRouteImport.update({
  id: '/expedicao',
  path: '/expedicao',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const OauthBlingCallbackRoute = OauthBlingCallbackRouteImport.update({
  id: '/oauth/bling/callback',
  path: '/oauth/bling/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlCallbackRoute = ApiMlCallbackRouteImport.update({
  id: '/api/ml/callback',
  path: '/api/ml/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlAuthRoute = ApiMlAuthRouteImport.update({
  id: '/api/ml/auth',
  path: '/api/ml/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugEtiquetaTesteRoute = ApiDebugEtiquetaTesteRouteImport.update({
  id: '/api/debug/etiqueta-teste',
  path: '/api/debug/etiqueta-teste',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConfiguracoesBlingRoute = AppConfiguracoesBlingRouteImport.update({
  id: '/bling',
  path: '/bling',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const ApiPublicHooksBlingSyncProductsRunRoute =
  ApiPublicHooksBlingSyncProductsRunRouteImport.update({
    id: '/api/public/hooks/bling-sync-products-run',
    path: '/api/public/hooks/bling-sync-products-run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBlingSyncProductsDailyRoute =
  ApiPublicHooksBlingSyncProductsDailyRouteImport.update({
    id: '/api/public/hooks/bling-sync-products-daily',
    path: '/api/public/hooks/bling-sync-products-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBlingRefreshRoute =
  ApiPublicHooksBlingRefreshRouteImport.update({
    id: '/api/public/hooks/bling-refresh',
    path: '/api/public/hooks/bling-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBlingPedidosRoute =
  ApiPublicHooksBlingPedidosRouteImport.update({
    id: '/api/public/hooks/bling-pedidos',
    path: '/api/public/hooks/bling-pedidos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/expedicao': typeof AppExpedicaoRoute
  '/pedidos': typeof AppPedidosRoute
  '/produtos': typeof AppProdutosRoute
  '/configuracoes/bling': typeof AppConfiguracoesBlingRoute
  '/api/debug/etiqueta-teste': typeof ApiDebugEtiquetaTesteRoute
  '/api/ml/auth': typeof ApiMlAuthRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/oauth/bling/callback': typeof OauthBlingCallbackRoute
  '/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/api/public/hooks/bling-pedidos': typeof ApiPublicHooksBlingPedidosRoute
  '/api/public/hooks/bling-refresh': typeof ApiPublicHooksBlingRefreshRoute
  '/api/public/hooks/bling-sync-products-daily': typeof ApiPublicHooksBlingSyncProductsDailyRoute
  '/api/public/hooks/bling-sync-products-run': typeof ApiPublicHooksBlingSyncProductsRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/expedicao': typeof AppExpedicaoRoute
  '/pedidos': typeof AppPedidosRoute
  '/produtos': typeof AppProdutosRoute
  '/configuracoes/bling': typeof AppConfiguracoesBlingRoute
  '/api/debug/etiqueta-teste': typeof ApiDebugEtiquetaTesteRoute
  '/api/ml/auth': typeof ApiMlAuthRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/oauth/bling/callback': typeof OauthBlingCallbackRoute
  '/configuracoes': typeof AppConfiguracoesIndexRoute
  '/api/public/hooks/bling-pedidos': typeof ApiPublicHooksBlingPedidosRoute
  '/api/public/hooks/bling-refresh': typeof ApiPublicHooksBlingRefreshRoute
  '/api/public/hooks/bling-sync-products-daily': typeof ApiPublicHooksBlingSyncProductsDailyRoute
  '/api/public/hooks/bling-sync-products-run': typeof ApiPublicHooksBlingSyncProductsRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expedicao': typeof AppExpedicaoRoute
  '/_app/pedidos': typeof AppPedidosRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/configuracoes/bling': typeof AppConfiguracoesBlingRoute
  '/api/debug/etiqueta-teste': typeof ApiDebugEtiquetaTesteRoute
  '/api/ml/auth': typeof ApiMlAuthRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/oauth/bling/callback': typeof OauthBlingCallbackRoute
  '/_app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/api/public/hooks/bling-pedidos': typeof ApiPublicHooksBlingPedidosRoute
  '/api/public/hooks/bling-refresh': typeof ApiPublicHooksBlingRefreshRoute
  '/api/public/hooks/bling-sync-products-daily': typeof ApiPublicHooksBlingSyncProductsDailyRoute
  '/api/public/hooks/bling-sync-products-run': typeof ApiPublicHooksBlingSyncProductsRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/expedicao'
    | '/pedidos'
    | '/produtos'
    | '/configuracoes/bling'
    | '/api/debug/etiqueta-teste'
    | '/api/ml/auth'
    | '/api/ml/callback'
    | '/oauth/bling/callback'
    | '/configuracoes/'
    | '/api/public/hooks/bling-pedidos'
    | '/api/public/hooks/bling-refresh'
    | '/api/public/hooks/bling-sync-products-daily'
    | '/api/public/hooks/bling-sync-products-run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/expedicao'
    | '/pedidos'
    | '/produtos'
    | '/configuracoes/bling'
    | '/api/debug/etiqueta-teste'
    | '/api/ml/auth'
    | '/api/ml/callback'
    | '/oauth/bling/callback'
    | '/configuracoes'
    | '/api/public/hooks/bling-pedidos'
    | '/api/public/hooks/bling-refresh'
    | '/api/public/hooks/bling-sync-products-daily'
    | '/api/public/hooks/bling-sync-products-run'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/expedicao'
    | '/_app/pedidos'
    | '/_app/produtos'
    | '/_app/configuracoes/bling'
    | '/api/debug/etiqueta-teste'
    | '/api/ml/auth'
    | '/api/ml/callback'
    | '/oauth/bling/callback'
    | '/_app/configuracoes/'
    | '/api/public/hooks/bling-pedidos'
    | '/api/public/hooks/bling-refresh'
    | '/api/public/hooks/bling-sync-products-daily'
    | '/api/public/hooks/bling-sync-products-run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDebugEtiquetaTesteRoute: typeof ApiDebugEtiquetaTesteRoute
  ApiMlAuthRoute: typeof ApiMlAuthRoute
  ApiMlCallbackRoute: typeof ApiMlCallbackRoute
  OauthBlingCallbackRoute: typeof OauthBlingCallbackRoute
  ApiPublicHooksBlingPedidosRoute: typeof ApiPublicHooksBlingPedidosRoute
  ApiPublicHooksBlingRefreshRoute: typeof ApiPublicHooksBlingRefreshRoute
  ApiPublicHooksBlingSyncProductsDailyRoute: typeof ApiPublicHooksBlingSyncProductsDailyRoute
  ApiPublicHooksBlingSyncProductsRunRoute: typeof ApiPublicHooksBlingSyncProductsRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedicao': {
      id: '/_app/expedicao'
      path: '/expedicao'
      fullPath: '/expedicao'
      preLoaderRoute: typeof AppExpedicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes/': {
      id: '/_app/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/oauth/bling/callback': {
      id: '/oauth/bling/callback'
      path: '/oauth/bling/callback'
      fullPath: '/oauth/bling/callback'
      preLoaderRoute: typeof OauthBlingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/callback': {
      id: '/api/ml/callback'
      path: '/api/ml/callback'
      fullPath: '/api/ml/callback'
      preLoaderRoute: typeof ApiMlCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/auth': {
      id: '/api/ml/auth'
      path: '/api/ml/auth'
      fullPath: '/api/ml/auth'
      preLoaderRoute: typeof ApiMlAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/etiqueta-teste': {
      id: '/api/debug/etiqueta-teste'
      path: '/api/debug/etiqueta-teste'
      fullPath: '/api/debug/etiqueta-teste'
      preLoaderRoute: typeof ApiDebugEtiquetaTesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/configuracoes/bling': {
      id: '/_app/configuracoes/bling'
      path: '/bling'
      fullPath: '/configuracoes/bling'
      preLoaderRoute: typeof AppConfiguracoesBlingRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/api/public/hooks/bling-sync-products-run': {
      id: '/api/public/hooks/bling-sync-products-run'
      path: '/api/public/hooks/bling-sync-products-run'
      fullPath: '/api/public/hooks/bling-sync-products-run'
      preLoaderRoute: typeof ApiPublicHooksBlingSyncProductsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bling-sync-products-daily': {
      id: '/api/public/hooks/bling-sync-products-daily'
      path: '/api/public/hooks/bling-sync-products-daily'
      fullPath: '/api/public/hooks/bling-sync-products-daily'
      preLoaderRoute: typeof ApiPublicHooksBlingSyncProductsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bling-refresh': {
      id: '/api/public/hooks/bling-refresh'
      path: '/api/public/hooks/bling-refresh'
      fullPath: '/api/public/hooks/bling-refresh'
      preLoaderRoute: typeof ApiPublicHooksBlingRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bling-pedidos': {
      id: '/api/public/hooks/bling-pedidos'
      path: '/api/public/hooks/bling-pedidos'
      fullPath: '/api/public/hooks/bling-pedidos'
      preLoaderRoute: typeof ApiPublicHooksBlingPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesBlingRoute: typeof AppConfiguracoesBlingRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesBlingRoute: AppConfiguracoesBlingRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpedicaoRoute: typeof AppExpedicaoRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppProdutosRoute: typeof AppProdutosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppExpedicaoRoute: AppExpedicaoRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppProdutosRoute: AppProdutosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDebugEtiquetaTesteRoute: ApiDebugEtiquetaTesteRoute,
  ApiMlAuthRoute: ApiMlAuthRoute,
  ApiMlCallbackRoute: ApiMlCallbackRoute,
  OauthBlingCallbackRoute: OauthBlingCallbackRoute,
  ApiPublicHooksBlingPedidosRoute: ApiPublicHooksBlingPedidosRoute,
  ApiPublicHooksBlingRefreshRoute: ApiPublicHooksBlingRefreshRoute,
  ApiPublicHooksBlingSyncProductsDailyRoute:
    ApiPublicHooksBlingSyncProductsDailyRoute,
  ApiPublicHooksBlingSyncProductsRunRoute:
    ApiPublicHooksBlingSyncProductsRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
